-- MySQL Script generated by MySQL Workbench
-- Sat Dec 31 09:55:42 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema regularExpressions
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema regularExpressions
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `regularExpressions` DEFAULT CHARACTER SET utf8 ;
USE `regularExpressions` ;

-- -----------------------------------------------------
-- Table `regularExpressions`.`WordsAndExpresions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regularExpressions`.`WordsAndExpresions` ;

CREATE TABLE IF NOT EXISTS `regularExpressions`.`WordsAndExpresions` (
  `id` INT NOT NULL,
  `word` VARCHAR(255) NOT NULL,
  `regularExpresion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

