-- MySQL Script generated by MySQL Workbench
-- Fri Feb  3 13:14:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema regularExpresions
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema regularExpresions
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `regularExpresions` DEFAULT CHARACTER SET utf8 ;
USE `regularExpresions` ;

-- -----------------------------------------------------
-- Table `regularExpresions`.`WordsAndExpresions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regularExpresions`.`WordsAndExpresions` ;

CREATE TABLE IF NOT EXISTS `regularExpresions`.`WordsAndExpresions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `word` VARCHAR(255) NOT NULL,
  `regularExpresion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
